ercot_username         = "jackbordelon23@gmail.com"
ercot_password         = "4710MMJb!!"
ercot_subscription_key = "8f2db5a2815b449e8a6edfd7c98b7ff1"
eia_key                = "bea836914490469da317004ada39604a"
