ercot_username         = "jackbordelon23@gmail.com"
ercot_password         = "4710MMJb!!"
ercot_subscription_key = "36a86c8e09604c668958238a78bd0fe7"
eia_key                = "ZWU4VRKiwMbBneB2CFRv0ATfDc5bQD9IAg9JvHNV"
