ercot_username         = "jackbordelon23@gmail.com"
ercot_password         = "4710MMJb!!"
ercot_subscription_key = "8f2db5a2815b449e8a6edfd7c98b7ff1"
eia_key                = "ZWU4VRKiwMbBneB2CFRv0ATfDc5bQD9IAg9JvHNV"
