ercot_username         = "your-email@example.com"
ercot_password         = "your-ercot-password"
ercot_subscription_key = "your-NEW-primary-key-after-regenerating"
eia_key                = "your-eia-key"
